version: '3'
services:

  redis5:
    image: redis:6
    command: "redis-server --port 6383  --dbfilename dump5.rdb"
    ports:
      - 6383

  redis6:
    image: redis:6
    command: "redis-server --protected-mode no --dbfilename dump6.rdb"
    ports:
      - 6379

  pwd-redis5:
    image: redis:6
    command: "redis-server --port 6380 --requirepass redis-password --dbfilename dump5-pwd.rdb"
    ports:
      - 6380

  pwd-redis6:
    image: redis:6
    command: "redis-server --port 6390 --requirepass dummy --user exporter on +CLIENT +INFO +SELECT +SLOWLOG +LATENCY '>exporter-password' --dbfilename dump6-pwd.rdb"
    ports:
      - 6390

  redis-2-8:
    image: redis:6.2
    command: "redis-server --port 6381 --dbfilename dump2-8.rdb"
    ports:
      - 6381

  keydb-01:
    image: "eqalpha/keydb:x86_64_v5.3.0"
    command: "keydb-server --protected-mode no --port 6401 --dbfilename dump-keydb-01.rdb"
    ports:
      - 6401

  keydb-02:
    image: "eqalpha/keydb:x86_64_v5.3.0"
    command: "keydb-server --protected-mode no --port 6402 --active-replica yes --replicaof keydb-01 6401  --dbfilename dump-keydb-02.rdb"
    ports:
      - 6402

  redis-cluster:
    image: grokzen/redis-cluster
    ports: [7000, 7001, 7002, 7003, 7004, 7005]

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:6.2-debian-10
    environment:
      - REDIS_MASTER_HOST=redis6
    ports:
      - 26379

  tile38:
    image: tile38/tile38:latest
    ports:
      - 9851


  tests:
    image: golang:1.17
    working_dir: /go/src/github.com/oliver006/redis_exporter
    volumes:
      - ..:/go/src/github.com/oliver006/redis_exporter
